### ISSUE TITLE
Adding comitters before initializing guet throws error log

### ISSUE THREAD

**Issue by chiptopher** [chiptopher/guet#16]
## Bug report
When trying to add a committer before running `guet init`, an unhelpful error log is thrown.

#### Actual behavior?
```
guet add cb "chris" chris@localhost
Traceback (most recent call last):
  File "/usr/local/bin/guet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/guet/main.py", line 23, in main
    executor.execute(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/guet/executor.py", line 26, in execute
    command.execute()
  File "/usr/local/lib/python3.6/dist-packages/guet/commands/addcommitter.py", line 42, in execute
    self._user_gateway.add_user(self._args[1], self._args[2], self._args[3])
  File "/usr/local/lib/python3.6/dist-packages/guet/gateways/gateway.py", line 184, in add_user
    if self.get_user(initials):
  File "/usr/local/lib/python3.6/dist-packages/guet/gateways/gateway.py", line 197, in get_user
    self._connection = sqlite3.connect(self._connection_path)
sqlite3.OperationalError: unable to open database file
```

#### Expected behavior?
Something helpful like
```
guet add cb "chris" chris@chris

guet has not been initialized yet! Please do so by running the command "guet init".
```

#### Environment:
Ubuntu 18.04.2

#### Notes
It might be helpful to include something like this for all commands that have to be ran after `guet init`.

**Comment by chiptopher** [comment]
`guet add` wont run without `guet init` having been called.
