### ISSUE TITLE
Bad error message when adding user before initializing

### ISSUE THREAD

**Issue by chiptopher** [chiptopher/guet#5]
## Bug report
When attempting to `guet add` without having done `guet init`, it prints a stack trace of the saying the database cannot be accessed.

#### Actual behavior?
```
(venv) ➜  ~ guet add us "name" email@localhost
Traceback (most recent call last):
  File "/home/user/workspace/guet/venv/bin/guet", line 11, in <module>
    load_entry_point('guet==1.0.0', 'console_scripts', 'guet')()
  File "/home/user/workspace/guet/venv/lib/python3.6/site-packages/guet-1.0.0-py3.6.egg/guet/main.py", line 22, in main
  File "/home/user/workspace/guet/venv/lib/python3.6/site-packages/guet-1.0.0-py3.6.egg/guet/executor.py", line 26, in execute
  File "/home/user/workspace/guet/venv/lib/python3.6/site-packages/guet-1.0.0-py3.6.egg/guet/commands/addcommitter.py", line 42, in execute
  File "/home/user/workspace/guet/venv/lib/python3.6/site-packages/guet-1.0.0-py3.6.egg/guet/gateway.py", line 108, in add_user
  File "/home/user/workspace/guet/venv/lib/python3.6/site-packages/guet-1.0.0-py3.6.egg/guet/gateway.py", line 121, in get_user
sqlite3.OperationalError: unable to open database file

```

#### Expected behavior?
An error message saying something to the effect of:
`You must initialize guet before adding committers!`

**Comment by chiptopher** [comment]
Same as #16
