### ISSUE TITLE
Unhelpful error message when set committers using unknown initials

### ISSUE THREAD

**Issue by chiptopher** [chiptopher/guet#7]
## Bug report
When calling `guet set` with initials not in the system it prints out a stack trace.

#### Actual behavior?
If there isn't a committer with the initials fi currently in the system, and a user calls `guet set fi`, then this is what the system will print:
```$ guet set fi
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/guet", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/guet/main.py", line 22, in main
    executor.execute(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/guet/executor.py", line 26, in execute
    command.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/guet/commands/setcommitters.py", line 37, in execute
    committers.append(CommitterInput(name=committer.name, email=committer.email))
AttributeError: 'NoneType' object has no attribute 'name'
```

#### Expected behavior?
It should say something like this:
```
$ guet set fi
No committer with the initials "fi".
```

#### Environment:
OS X with python 3.

**Comment by chiptopher** [comment]
Closed by #9
